In [1]:
# Import needed libraries

import pandas as pd
import numpy as np
from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()
%matplotlib inline

In [2]:
# Load the dataset
filename = "./data/raw_data.csv"
df_raw = pd.read_csv(filename, sep= ",")
df_raw.head()

,Numéro d'identification / Number ID,Date Received / Date reçue,Complaint Received Type,Type de plainte reçue,Country,Pays,Province/State,Province/État,Fraud and Cybercrime Thematic Categories,Catégories thématiques sur la fraude et la cybercriminalité,...,Méthode de sollicitation,Gender,Genre,Language of Correspondence,Langue de correspondance,Victim Age Range / Tranche d'âge des victimes,Complaint Type,Type de plainte,Number of Victims / Nombre de victimes,Dollar Loss /pertes financières
0,1,2021-01-02,CAFC Website,CAFC site web,Canada,Canada,Saskatchewan,Saskatchewan,Merchandise,Marchandise,...,Autre/inconnu,Not Available,non disponible,Not Available,non disponible,'Not Available / non disponible,Attempt,Tentative,0,$0.00
1,2,2021-01-02,CAFC Website,CAFC site web,Not Specified,Non spécifié,Not Specified,Non spécifié,Merchandise,Marchandise,...,Internet,Not Available,non disponible,Not Available,non disponible,'Not Available / non disponible,Victim,Victime,1,"$1,000.00"
2,3,2021-01-02,CAFC Website,CAFC site web,Canada,Canada,Quebec,Québec,Identity Fraud,Fraude à l'identité,...,Autre/inconnu,Male,Homme,French,Français,'40 - 49,Victim,Victime,1,$0.00
3,4,2021-01-02,CAFC Website,CAFC site web,Canada,Canada,Saskatchewan,Saskatchewan,Phishing,Hameçonnage,...,Courriel,Male,Homme,English,Anglais,'30 - 39,Victim,Victime,1,$0.00
4,5,2021-01-02,CAFC Website,CAFC site web,Canada,Canada,Saskatchewan,Saskatchewan,Merchandise,Marchandise,...,Autre/inconnu,Male,Homme,Not Available,non disponible,'60 - 69,Victim,Victime,1,$222.73

In [3]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328649 entries, 0 to 328648
Data columns (total 21 columns):
 #   Column                                                       Non-Null Count   Dtype
---  ------                                                       --------------   -----
 0   Numéro d'identification / Number ID                          328649 non-null  int64
 1   Date Received / Date reçue                                   328649 non-null  object
 2   Complaint Received Type                                      328649 non-null  object
 3   Type de plainte reçue                                        328649 non-null  object
 4   Country                                                      328649 non-null  object
 5   Pays                                                         328649 non-null  object
 6   Province/State                                               328649 non-null  object
 7   Province/État                                                328649 non-null  object
 8   Fraud and Cybercrime Thematic Categories                     328649 non-null  object
 9   Catégories thématiques sur la fraude et la cybercriminalité  328649 non-null  object
 10  Solicitation Method                                          328649 non-null  object
 11  Méthode de sollicitation                                     328649 non-null  object
 12  Gender                                                       328649 non-null  object
 13  Genre                                                        328649 non-null  object
 14  Language of Correspondence                                   328649 non-null  object
 15  Langue de correspondance                                     328649 non-null  object
 16  Victim Age Range / Tranche d'âge des victimes                328649 non-null  object
 17  Complaint Type                                               328649 non-null  object
 18  Type de plainte                                              328649 non-null  object
 19  Number of Victims / Nombre de victimes                       328649 non-null  int64
 20  Dollar Loss /pertes financières                              328649 non-null  object
dtypes: int64(2), object(19)
memory usage: 52.7+ MB

**Notes:**
- No null values detected.

# Preprocessing
- Remove columns with french translation.
- Convert Dollar Loss to numeric. 
- Convert date column to date

In [4]:
df_mod = df_raw.copy()

to_drop = ["Type de plainte reçue", "Pays", "Province/État", "Catégories thématiques sur la fraude et la cybercriminalité", "Méthode de sollicitation",
           "Genre", "Genre", "Type de plainte", "Langue de correspondance"]

df_mod = df_mod.drop(columns=to_drop, axis = 0)
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328649 entries, 0 to 328648
Data columns (total 13 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Numéro d'identification / Number ID            328649 non-null  int64
 1   Date Received / Date reçue                     328649 non-null  object
 2   Complaint Received Type                        328649 non-null  object
 3   Country                                        328649 non-null  object
 4   Province/State                                 328649 non-null  object
 5   Fraud and Cybercrime Thematic Categories       328649 non-null  object
 6   Solicitation Method                            328649 non-null  object
 7   Gender                                         328649 non-null  object
 8   Language of Correspondence                     328649 non-null  object
 9   Victim Age Range / Tranche d'âge des victimes  328649 non-null  object
 10  Complaint Type                                 328649 non-null  object
 11  Number of Victims / Nombre de victimes         328649 non-null  int64
 12  Dollar Loss /pertes financières                328649 non-null  object
dtypes: int64(2), object(11)
memory usage: 32.6+ MB

**Notes:**
- We have reduced the number of columns to 13.

In [5]:
df_mod["Dollar Loss"] = df_mod["Dollar Loss /pertes financières"].apply(lambda x: x.replace("$", ""))
df_mod["Dollar Loss"] = df_mod["Dollar Loss"].apply(lambda x: x.replace(",", ""))
df_mod["Dollar Loss"] = df_mod["Dollar Loss"].astype(float)
df_mod["Dollar Loss"].head()

0       0.00
1    1000.00
2       0.00
3       0.00
4     222.73
Name: Dollar Loss, dtype: float64

In [6]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328649 entries, 0 to 328648
Data columns (total 14 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Numéro d'identification / Number ID            328649 non-null  int64
 1   Date Received / Date reçue                     328649 non-null  object
 2   Complaint Received Type                        328649 non-null  object
 3   Country                                        328649 non-null  object
 4   Province/State                                 328649 non-null  object
 5   Fraud and Cybercrime Thematic Categories       328649 non-null  object
 6   Solicitation Method                            328649 non-null  object
 7   Gender                                         328649 non-null  object
 8   Language of Correspondence                     328649 non-null  object
 9   Victim Age Range / Tranche d'âge des victimes  328649 non-null  object
 10  Complaint Type                                 328649 non-null  object
 11  Number of Victims / Nombre de victimes         328649 non-null  int64
 12  Dollar Loss /pertes financières                328649 non-null  object
 13  Dollar Loss                                    328649 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 35.1+ MB

In [7]:
#Convert date to datetime format
df_mod["Date"] = pd.to_datetime(df_mod["Date Received / Date reçue"])
df_mod["Date"].head()

0   2021-01-02
1   2021-01-02
2   2021-01-02
3   2021-01-02
4   2021-01-02
Name: Date, dtype: datetime64[ns]

In [8]:
# Just in case
df_mod = df_mod.drop_duplicates(subset = "Numéro d'identification / Number ID")
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328649 entries, 0 to 328648
Data columns (total 15 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Numéro d'identification / Number ID            328649 non-null  int64
 1   Date Received / Date reçue                     328649 non-null  object
 2   Complaint Received Type                        328649 non-null  object
 3   Country                                        328649 non-null  object
 4   Province/State                                 328649 non-null  object
 5   Fraud and Cybercrime Thematic Categories       328649 non-null  object
 6   Solicitation Method                            328649 non-null  object
 7   Gender                                         328649 non-null  object
 8   Language of Correspondence                     328649 non-null  object
 9   Victim Age Range / Tranche d'âge des victimes  328649 non-null  object
 10  Complaint Type                                 328649 non-null  object
 11  Number of Victims / Nombre de victimes         328649 non-null  int64
 12  Dollar Loss /pertes financières                328649 non-null  object
 13  Dollar Loss                                    328649 non-null  float64
 14  Date                                           328649 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(11)
memory usage: 37.6+ MB

In [9]:
df_clean_up = df_mod.copy()
df_clean_up = df_clean_up.drop(columns=["Dollar Loss /pertes financières", "Date Received / Date reçue"], axis = 1)

In [10]:
# Let's explore categorical values
var_cats = [col for col in df_clean_up.columns if df_clean_up[col].dtype == "object"]
df_categorical = df_clean_up[var_cats]

for col in df_categorical.columns:
    most_frequent = df_categorical[col].value_counts()[:5]  # Top 5
    print(f"\n=={col}==")
    print(most_frequent)

==Complaint Received Type==
Complaint Received Type
CAFC Website    174178
Phone           116794
Email            21633
NCFRS            15537
Other              424
Name: count, dtype: int64

==Country==
Country
Canada            249795
Not Specified      74367
United States       2074
India                245
United Kingdom       157
Name: count, dtype: int64

==Province/State==
Province/State
Ontario             96150
Not Specified       77767
Quebec              67041
British Columbia    31604
Alberta             26189
Name: count, dtype: int64

==Fraud and Cybercrime Thematic Categories==
Fraud and Cybercrime Thematic Categories
Identity Fraud    75475
Extortion         31444
Phishing          28433
Personal Info     26847
Service           25225
Name: count, dtype: int64

==Solicitation Method==
Solicitation Method
Other/unknown              95692
Direct call                77299
Email                      37102
Internet-social network    36537
Internet                   31204
Name: count, dtype: int64

==Gender==
Gender
Female               123639
Male                 119076
Not Available         84113
Unknown                1065
Prefer not to say       485
Name: count, dtype: int64

==Language of Correspondence==
Language of Correspondence
English          182023
Not Available     84555
French            62071
Name: count, dtype: int64

==Victim Age Range / Tranche d'âge des victimes==
Victim Age Range / Tranche d'âge des victimes
'Not Available / non disponible    98111
'30 - 39                           43124
'60 - 69                           37931
'40 - 49                           37604
'20 - 29                           34941
Name: count, dtype: int64

==Complaint Type==
Complaint Type
Victim        212984
Attempt       108038
Other           6128
Unknown         1026
Incomplete       473
Name: count, dtype: int64

**Notes:**
With these results we can identify anomalies in the categorical values. Although no anomalies have been detected, we can observe that:
- Unkown and Not Available should be grouped and fall under the same category.
- Most of the complaints are comming through the CAFC Website and Phone.
- Most of the attacks are originated in Canada.
- Identity Fraud is the most common type of attack.
- A direct phone call is the prefferred attack method for the attackers.
- English is the most used language by the attackers. 

These will be further analyzed later.

In [11]:
# Let's see how numerical values distribute
df_clean_up.describe()

,Numéro d'identification / Number ID,Number of Victims / Nombre de victimes,Dollar Loss,Date
count,328649.000000,328649.000000,3.286490e+05,328649
mean,164325.000000,0.648059,6.996873e+03,2022-10-05 17:18:51.486784
min,1.000000,0.000000,0.000000e+00,2021-01-02 00:00:00
25%,82163.000000,0.000000,0.000000e+00,2021-09-28 00:00:00
50%,164325.000000,1.000000,0.000000e+00,2022-08-01 00:00:00
75%,246487.000000,1.000000,0.000000e+00,2023-09-05 00:00:00
max,328649.000000,1.000000,2.361500e+07,2025-03-28 00:00:00
std,94872.938647,0.477576,1.023280e+05,NaN

**Notes:**
- The attacks usually involve 1 victim as a max. 
- The minimum date is 01/02/2021 and the latest date is 28/03/2025.

In [12]:
df_clean_up.describe().apply(lambda s: s.apply("{0:.5f}".format))

,Numéro d'identification / Number ID,Number of Victims / Nombre de victimes,Dollar Loss,Date
count,328649.00000,328649.00000,328649.00000,328649.00000
mean,164325.00000,0.64806,6996.87277,.5f
min,1.00000,0.00000,0.00000,.5f
25%,82163.00000,0.00000,0.00000,.5f
50%,164325.00000,1.00000,0.00000,.5f
75%,246487.00000,1.00000,0.00000,.5f
max,328649.00000,1.00000,23615000.00000,.5f
std,94872.93865,0.47758,102328.00048,nan

**Notes:**
- The average dollar loss is around $7000.
- The standard deviation is pretty high, meaning we will see different amounts of loss.
- The maximum loss was $23M, that is a huge amount. Let's double check it is not an error.

In [13]:
df_clean_up[df_clean_up["Dollar Loss"] > 23000000]

,Numéro d'identification / Number ID,Complaint Received Type,Country,Province/State,Fraud and Cybercrime Thematic Categories,Solicitation Method,Gender,Language of Correspondence,Victim Age Range / Tranche d'âge des victimes,Complaint Type,Number of Victims / Nombre de victimes,Dollar Loss,Date
280810,280811,Email,Canada,Manitoba,Unknown,Not Available,Not Available,Not Available,'Not Available / non disponible,Victim,1,23615000.0,2024-04-29

**Notes:**
- With this information we can see it was an atttack carried reported the 29/04/2024 and sourced in Canada. No more information is detailed.

# NA Treatment
In this section I will map those values which point to missing data and remove them from the dataset.

In [22]:
# Grouping Not available, Unknown, Incomplete, etc. 
values_nan = ["Incomplete", "Unknown", "Not Specified", "'Not Available / non disponible", "Not Available"]
df_clean_up[var_cats] = df_clean_up[var_cats].replace(values_nan, np.nan)

In [23]:
df_clean_up.isna().sum() * 100 / len(df_clean_up)

Numéro d'identification / Number ID               0.000000
Complaint Received Type                           0.005173
Country                                          22.633874
Province/State                                   23.662631
Fraud and Cybercrime Thematic Categories          2.992859
Solicitation Method                               5.290447
Gender                                           25.917620
Language of Correspondence                       25.728056
Victim Age Range / Tranche d'âge des victimes    29.852822
Complaint Type                                    0.456110
Number of Victims / Nombre de victimes            0.000000
Dollar Loss                                       0.000000
Date                                              0.000000
dtype: float64

**Notes:**
- Number of NaNs has increased as expected.
- Victim Age Range shows a great number of null values, followed by Country and State.

For the purpose of the project, an Ad Hoc analysis, I will keep these null values and explore why are complaints missing this information.

# Final Cleanup
For this final cleanup I will rename the columns and remove duplicated ones.

In [16]:
df_clean_up.columns

Index(['Numéro d'identification / Number ID', 'Complaint Received Type',
       'Country', 'Province/State', 'Fraud and Cybercrime Thematic Categories',
       'Solicitation Method', 'Gender', 'Language of Correspondence',
       'Victim Age Range / Tranche d'âge des victimes', 'Complaint Type',
       'Number of Victims / Nombre de victimes', 'Dollar Loss', 'Date'],
      dtype='object')

In [25]:
df_final = df_clean_up.copy()
df_final = df_final.rename({"Numéro d'identification / Number ID":"Case ID",
                 "Victim Age Range / Tranche d'âge des victimes":"Victim Age Range",
                 "Number of Victims / Nombre de victimes": "Number of Victims"}, axis = 1)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328649 entries, 0 to 328648
Data columns (total 13 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Case ID                                   328649 non-null  int64
 1   Complaint Received Type                   328632 non-null  object
 2   Country                                   254263 non-null  object
 3   Province/State                            250882 non-null  object
 4   Fraud and Cybercrime Thematic Categories  318813 non-null  object
 5   Solicitation Method                       311262 non-null  object
 6   Gender                                    243471 non-null  object
 7   Language of Correspondence                244094 non-null  object
 8   Victim Age Range                          230538 non-null  object
 9   Complaint Type                            327150 non-null  object
 10  Number of Victims                         328649 non-null  int64
 11  Dollar Loss                               328649 non-null  float64
 12  Date                                      328649 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 32.6+ MB

In [27]:
df_final.to_csv("./data/clean_data.csv", index= False)